# app overall settings
app:
  name: ${APP_NAME|SB_USERS}
  template_dir: ${TEMPLATE_DIR|internal/templates/emails/}
  auth_key: ${APP_AUTH_KEY|123456}

# logger settings
logger:
  level: ${LOG_LEVEL|debug}

# Database connection settings
db:
  username: ${POSTGRES_USER|postgres}
  host: ${POSTGRES_HOST|localhost}
  port: ${POSTGRES_PORT|5432}
  dbname: ${POSTGRES_DB|dbname}
  password: ${POSTGRES_PASSWORD|secretpassword}
  sslMode: "disable"

rest:
  port: ${REST_PORT|8080}
  readTimeout: ${REST_READ_TIMEOUT|15} # seconds
  writeTimeout: ${REST_WRITE_TIMEOUT|15} # seconds
  maxHeaderBytes: ${REST_MAX_HEADER_BYTES|1048576} # 1mb

mail:
  host: ${MAIL_SMTP_HOST|smtp.gmail.com}
  port: ${MAIL_SMTP_PORT|587}
  from: ${MAIL_SMTP_FROM|some@email.com}
  user: ${MAIL_SMTP_USER|someuser}
  password: ${MAIL_SMTP_PASSWORD|somepwd}